Votes
aamnesia/qnaa pull request #4
Opened 2022-04-11 07:10 UTC by aamnesia

2022-04-11 08:25 UTC, vkurennov requested changes

2022-04-11 08:25 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    return render_errors if current_user.author?(@votable)
тут правило как раз обратное: отменить голос может только тот, кто его подал

2022-04-11 08:25 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    votes.destroy_all if vote_of?(user)
в таком случае удалятся вообще все голоса за объект, даже если они не от этого юзера.  то есть условие здесь является лишь условием того, выполняется  destroy_all или нет, но на само попведение этого метода влияния не оказывает.

И прежде чем это исправлять, нужно написать тест, который бы такой кейс подтвердил: т.е. создаются голоса не только от этого юзера, но и от других, тест проверяет, что другие голоса не были удалены. подтверждение кейса == упавший тест, а когда поправишь код, пройдет и тест.
так с любыми багами поступать надо: написать тест, которые этот баг проверяет, так, чтобы тест упал. а потом поправитт код так, чтобы тест прошел и тем самым исправить баг

2022-04-11 09:11 UTC, aamnesia commented on app/controllers/concerns/voted.rb
> +    return render_errors if current_user.author?(@votable)
изменила votable на resource для читаемости, здесь проверка на авторство вопроса/ответа

2022-04-12 06:34 UTC, aamnesia commented on app/controllers/concerns/voted.rb
> +    return render_errors if current_user.author?(@votable)
Лучше убрать? Во вью автору не показывается возможность голосовать

2022-04-12 10:41 UTC, vkurennov approved these changes

2022-04-12 10:41 UTC, vkurennov commented on spec/support/shared_examples/votable.rb
> +    expect(votable.rating).to eq -1
тут надо бы проверить, что удален именно голос нужного юзера

2022-05-18 19:10 UTC, merged